### ISSUE TITLE
How to restore the SWD state to its start-up state

### ISSUE THREAD

**Issue by fig-shimooka** [ezWheelSAS/swd_ros_controllers#10]
Is there a way to restore the SWD state to the state immediately after start-up?
If only the PC is restarted with power on to the motor, the PDS status may become False.
We assume that this is caused by the reboot ignoring the state of the motor.
So when I reboot, I want to return the motor state to the state immediately after start-up.
How can I do this?

**Comment by ez-Support** [comment]
The pc is the canopen master, so the two swd-motors turn to NMT PRE-OPERATIONAL, as the master was turned off.
When the ezw-ros-controller is started, it sends the commands to the motor, to go to NMT State OPERATIONNAL

**Comment by fig-shimooka** [comment]
Sorry. It seems that ezw-ros-bringup failed to start. (Due to my environment).
After correcting my environment, it now works as expected.
