### ISSUE TITLE
Is there an abnormality detection circuit?

### ISSUE THREAD

**Issue by fig-shimooka** [ezWheelSAS/swd_ros_controllers#15]
Does SWD Core have a function to detect abnormalities in the event of an electrical circuit failure (e.g. circuit short circuit)?
Does the motor stop when an abnormality is detected?

**Comment by ez-Support** [comment]
Yes the motor will detect any over/under current/voltage. In that case, it will stop the motor immediatly.

**Comment by fig-shimooka** [comment]
Thank you! This question has been resolved.
