### ISSUE TITLE
I want to disable the emergency switch connected to the right motor.

### ISSUE THREAD

**Issue by fig-shimooka** [ezWheelSAS/swd_ros_controllers#22]
I want to disable the emergency switch connected to the right motor.
How do I change the settings in swd_right_commissioning.py?

**Comment by ez-Support** [comment]
You gotta comment those 2 lines, in swd_right_5_commissioning.py (l.73-74), AND in swd_left_4_commissioning.py (l.41-42)
```
    scwMapping[0] = SafetyFunctionId.STO
    scwMapping[1] = SafetyFunctionId.STO
```

As the information of STO from SWD right, is not transmitted and read in SWD left anymore

**Comment by fig-shimooka** [comment]
Thank you. This issue has been resolved.
