### ISSUE TITLE
How do I set up commision when two SE2Ls are connected individually?

### ISSUE THREAD

**Issue by fig-shimooka** [ezWheelSAS/swd_ros_controllers#26]
How do I set up commision when two SE2Ls are connected individually?

The front SE2L is INSafe_1 for OSSD1⇔SWD1, 
INSafe_2 for OSSD2⇔SWD1, INSafe_3 for OSSD3⇔SWD1, and
INSafe_3 for OSSD3⇔SWD1, INSafe_4 for OSSD4⇔SWD1.

The rear SE2L is INSafe_1 for OSSD1⇔SWD2, 
INSafe_2 for OSSD2⇔SWD2, and INSafe_4 for OSSD3⇔SWD1.
INSafe_3 for OSSD3⇔SWD2, INSafe_4 on the OSSD4⇔SWD2.

The current setup is this.
[ezw.zip](https://github.com/ezWheelSAS/swd_ros_controllers/files/9109518/ezw.zip)

**Comment by ez-Support** [comment]
I assume you want to have the same configuration of the safety fonctions for the front and the rear laser scanner.
Thus, you should configure the SWD motors, as the following:
[commissioning.zip](https://github.com/ezWheelSAS/swd_ros_controllers/files/9130204/commissioning.zip)
