### ISSUE TITLE
How can I check the SWD firmware version?

### ISSUE THREAD

**Issue by suguruhamada1003910** [ezWheelSAS/swd_ros_controllers#31]
![SWDfirmwareVersion](https://user-images.githubusercontent.com/101627039/182785103-6dfacadc-2413-4bbf-9cac-d7b9b7fbbf8f.png)

I would like to use the latest source code. Then, I noticed that firmware version must be greater than v1.0.1.
How can I check the version?

**Comment by ez-Support** [comment]
You can have access to this information through the remote diagnostic, it corresponds to the line "SWVersion" :
`~/remote.py swd_right
~/remote.py swd_left`

**Comment by suguruhamada1003910** [comment]
I got it. Then, SWD version is V1.0.1. Should I upgrade firmware version? "SWD firmware (> 1.0.1)" means it must be 1.0.2 or bigger?

**Comment by ez-Support** [comment]
I think '=' is missing. SWD firmware version V1.0.1 should be fine 😉!

**Comment by suguruhamada1003910** [comment]
Thanks. I created pull request.
