### ISSUE TITLE
Do you have plan to support arm64?

### ISSUE THREAD

**Issue by suguruhamada1003910** [ezWheelSAS/swd_ros_controllers#33]
I am using arm64 now and I realized that the CPU is not available with swd_ros_controllers for now.
Do you have any plan of support?

**Comment by GMezWheel** [comment]
For information, you can install the pre-released version of swd-services for arm64.
=> swd-services_0.2.6_arm64.deb

Then recompile swd_ros_controllers from source.

**Comment by suguruhamada1003910** [comment]
Thank you for reply. I would like to use tag v2.0.0 of swd_ros_controllers. Is it possible?

**Comment by GMezWheel** [comment]
No. It is possible from the version v3.0.0.
Indeed, v2.0.0 is compatible with swd-service 0.1.x.

**Comment by suguruhamada1003910** [comment]
Thank you!
