### ISSUE TITLE
How can I measure the distance SWD has traveled?

### ISSUE THREAD

**Issue by suguruhamada1003910** [ezWheelSAS/swd_ros_controllers#39]
I would like to create program which SWD repeats forward and backward. Then, I would like to specify the distance of forward and backward.
I thought I can calculate the distance from the elapsed time and the speed but SWD increments speed gradually. Therefore, I thought I need the value of encoder.

Is it possible that I get the value of encoder? And if there is easy way to calculate the distance, please tell me.

**Comment by GMezWheel** [comment]
Hi @suguruhamada1003910 ,

Have a look at cbTimerOdom function of the DiffDriveController ROS node. 
This function gets the odometry encoder value of each motors and compute new distance/theta in order to send odom topic.

**Comment by suguruhamada1003910** [comment]
Hi @GMezWheel 

I think `d_dist_left` and `d_dist_left` are the distance (m). Is it right?

**Comment by GMezWheel** [comment]
Yes. 
* _mm means millimeters
* _m means meters

Thus d_dist_left_m et d_dist_right_m are the distance in meter.

**Comment by suguruhamada1003910** [comment]
Thanks!!
