### ISSUE TITLE
Where can I get "libezw-smc-core.so"?

### ISSUE THREAD

**Issue by fig-shimooka** [ezWheelSAS/swd_ros_controllers#4]
I am trying to compile from source code following the instructions here.
https://github.com/ezWheelSAS/swd_ros_controllers

When I run "roslaunch swd_ros_controllers swd_diff_drive_controller.launch" I get an error saying "libezw-smc-core.so" not found.
Where can I get "libezw-smc-core.so"?

**Comment by stakakusu** [comment]
I encountered the same issue and 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH":/opt/ezw/usr/lib" ' solved this.
