### ISSUE TITLE
USB hub for starter kit

### ISSUE THREAD

**Issue by JacquesRoubaud** [ezWheelSAS/swd_ros_controllers#40]
Hello
Do you recommend a particular USB hub model/brand that would be recognized by the LINUX platform of the starter kit ? 
The idea is to be able to connect keyboard, bluetooth, possibly a camera... 

thank you

**Comment by ez-Support** [comment]
Hi,

There is no recommanded brand for a USB hub, it should work with a "standard" brand.

**Comment by JacquesRoubaud** [comment]
thanks!
