### ISSUE TITLE
Disabling the brakes on the SWD

### ISSUE THREAD

**Issue by HirokiShikazaki** [ezWheelSAS/swd_ros_controllers#51]
When SWD is turned off, the brakes are enabled for 20 minutes.
Is there a way to disable this in software?

The brake is released 20 minutes after the SWD is turned off.
After the brake is released, there is a sensation that the rotation of the wheels becomes progressively heavier when the cart with the SWD is moved manually.
At this time, the OK light was blinking red. Was the brake effective?

**Comment by ez-Support** [comment]
From firmware release 1.1.4, the SWD will not have brake enabled for 20 minutes after being turned off anymore, and will be in free wheel. 
You will have to wait for the next firwmare realease to correct this problem.
