### ISSUE TITLE
Inaccurate odometry positionning using SWD StarterKit

### ISSUE THREAD

**Issue by NathanPixiel** [ezWheelSAS/swd_ros_controllers#56]
Hi
I've seen inaccurate odometry positionning using SWD StarterKit on ROS1.

I did several odometry tests.
I turned on the kit on a mark on the ground, rolled 25 meters forward, rotate 180 degrees clockwise, then 25 meters forward back to my mark on the ground. The position raised on the topic of /odom is x=0.019m but y=0.620m.
Then I did the same test again but with 1620 degrees clockwise at the end of the straight line. Readings are worse (x=0.321m and y=2.250m).

I attached a link to download bag files that are ros2 bag files because i'm using a bridge between imx6 and my PC.
https://we.tl/t-kx08TLjga4

Do you have any idea to resolve this problem?

Regards,
Nathan

**Comment by abougouffa** [comment]
Hello @NathanPixiel,

I've just checked your bag files, the odometry is there, you are just using the wrong topic.

You should use the `/swd_diff_drive_controller/odom` topic instead of `/odom`.

Abdelhak

**Comment by NathanPixiel** [comment]
Thank you for this quick response,

`/odom` topic is a copy of `/swd_diff_drive_controller/odom` topic
I'm just using `/odom` this to display on Rviz2, changing `child_frame_id` and `timestamp`.

![odom_topics](https://user-images.githubusercontent.com/74545724/205339374-1b68201b-d348-4e25-919c-b376b53cc799.png)

So the problem is present on `/swd_diff_drive_controller/odom` received from imx6.

Nathan

**Comment by ez-Support** [comment]
We are actively working on this issue. A solution will be provided by the end of the year.
