### ISSUE TITLE
What does "HardwareHelper;device" mean?

### ISSUE THREAD

**Issue by fig-shimooka** [ezWheelSAS/swd_ros_controllers#6]
What does device in the /opt/ezw/data/configuration.json file refer to?
By default, /dev/ttyUSBY and /dev/ttyUSBX are specified, but there is no actual situation.

**Comment by GMezWheel** [comment]
This entry is actually not used as the motors are not connected by usb cable to the IPC.

**Comment by fig-shimooka** [comment]
Thank you very much.
It was helpful.
