### ISSUE TITLE
When ROS program is stopped by pressing Ctrl+C, SWD keeps running

### ISSUE THREAD

**Issue by suguruhamada1003910** [ezWheelSAS/swd_ros_controllers#63]
I sometimes confirm that SWD keeps running when ROS program is stopped by pressing Ctrl+C.
I would like to stop SWD always when pressing Ctrl+C. Do you have any solution?

**Comment by ez-Support** [comment]
For exiting the ROS program it might be necessary to press a few times `ctrl+c`, in order to exit the program as several loops are executed within the script.

**Comment by ez-Support** [comment]
Otherwise, you can kill all ros nodes: `rosnode kill -a`,
Or the ros master node: `killall -9 roscore` or `killall -9 rosmaster`

**Comment by suguruhamada1003910** [comment]
@GMezWheel 

I confirmed the behavior and SWD is stopped perfectly!! Thank you for improvement.
