### ISSUE TITLE
How can I four SWDs with one PC?

### ISSUE THREAD

**Issue by suguruhamada1003910** [ezWheelSAS/swd_ros_controllers#67]
I read the following link but I cannot resolve my issue.

[Control two starter kits from one PC](https://github.com/ezWheelSAS/swd_ros_controllers/issues/65)

When I control 4 SWDs with one PC, I think there are two method.

1. Controlling two `swd_ros_controllers` nodes in two PC from one PC
![image](https://user-images.githubusercontent.com/101627039/230314175-f1d918d8-5c9f-4e40-9147-c6eb83fcc654.png)

2. Controlling two `swd_ros_controllers` nodes in one PC
![image](https://user-images.githubusercontent.com/101627039/230314230-7154391f-15af-48b9-8087-cb955332c549.png)

I think I can create method 1.
Can I create method 2?

I am thinking I can create method 2 by creating two `ezw-swd-left.service` and two `ezw-swd-right.service` in one PC.

**Comment by ez-Support** [comment]
Warning CAN IDs 6 and 7, are used by the swd services instances. Thus i recommand using IDs 0x14 and 0x15 for the 2 additional wheels ;)

**Comment by ez-Support** [comment]
What is the set-up of your wheels on the robot ?

**Comment by suguruhamada1003910** [comment]
`Warning CAN-IDs 0x6 and 0x7 are used by the swd services instances (in the IPC). Thus I recommand using IDs 0x14 and 0x15 for the 2 additional wheels ;) As a reminder, CAN-IDs must be unique on the CANopen bus field.`
Thank you for advice!!

`What is the set-up of your wheels on the robot ?`
I am not sure the meaning of your question but I try to explain the details.
My robot needs to carry very heavy object. The power of SWD is not enough. Therefore, I am thinking I equip four wheels in my robot.

**Comment by ez-Support** [comment]
Ok! What is the load to move and the maximum speed required ?

**Comment by suguruhamada1003910** [comment]
> Ok! What is the load to move and the maximum speed required ?
I am checking information.

By the way, what do you think method 2? Do you have another the best way?

**Comment by suguruhamada1003910** [comment]
> Ok! What is the load to move and the maximum speed required ?

Please check below.

```
maximum speed：1m/s
for one starter kit, load will be around 120kg
for one starter kit, load will be around 240kg
vertical load: max. 30kg per axis
```

**Comment by ez-Support** [comment]
So the total load will be < 500kg?

**Comment by ez-Support** [comment]
Yes method2 looks better.

**Comment by suguruhamada1003910** [comment]
I correct information of AMR.

```
maximum speed：1m/s
for one starter kit, load will be around 120kg
for two starter kit, load will be around 240kg
vertical load: max. 30kg per axis
Size of Wheel: 200mm

User want to keep 1m/s when loading 360kg.
```

>I really do think using 2xSWD-125 or 2xSWD-150 would be much easier to implement in that case.
>Why using a 4x wheel drive set-up here ?
SWD125 is not selling in Japan for now.

**Comment by suguruhamada1003910** [comment]
I don't have any query for now. I close this.

**Comment by suguruhamada1003910** [comment]
Hi Support, I am creating the following configuration.

![image](https://user-images.githubusercontent.com/101627039/231911607-7e51a514-e485-4bc6-8841-820b487e6053.png)

Then, I can communicate with four SWDs by using remote.py.
However, I could not control four SWDs. Specifically, only 2 SWDs are running by joy.

I am thinking dbus session is not specified correctly. In the following code, only one DBUS_SESSION_BUS_ADDRESS can be specified.
https://github.com/ezWheelSAS/swd_ros2_controllers/blob/main/launch/swd_diff_drive_controller.launch.py#L17-L25

If I write code as below, DBUS_SESSION_BUS_ADDRESS is overwritten and PC can communicate with only one session.

```
    # Load specific dbus user session if exists
    session = "/tmp/SYSTEMCTL_dbus.id"
    if os.path.isfile(session):
        print("SYSTEMCTL_dbus.id detected")

        with open(session) as f:
            lines = f.readlines()
        env = dict(line.strip().split("=", 1) for line in lines)
        os.environ.update(env)

    # Load specific dbus user session if exists
    session = "/tmp/SYSTEMCTL_dbus2.id"
    if os.path.isfile(session):
        print("SYSTEMCTL_dbus2.id detected")

        with open(session) as f:
            lines = f.readlines()
        env = dict(line.strip().split("=", 1) for line in lines)
        os.environ.update(env)
```

I want to specify SYSTEMCTL_dbus.id for CAN ID 4 and5 and SYSTEMCTL_dbus2.id for CAN ID 14 and 15. Do you have any idea?

**Comment by suguruhamada1003910** [comment]
The delay is needed to avoid overwritten DBUS_SESSION_BUS_ADDRESS.

```
TimerAction(
         period=5.0,
         actions=[
               swd_diff_drive_controller_description2(),
         ]),
```
