### ISSUE TITLE
How to disable CAN bus termination resistance?

### ISSUE THREAD

**Issue by suguruhamada1003910** [ezWheelSAS/swd_ros_controllers#77]
In SWD Core manual, it is written that "CAN bus termination resistance is configuable". 

![image](https://github.com/ezWheelSAS/swd_ros_controllers/assets/101627039/3dea12a7-f410-4cf1-845d-37209f6f2f8a)

Would you tell me the method?

**Comment by ez-Support** [comment]
Yes of course, thanks for asking. Be aware that by default, the internal CAN bus resistor is activated.
The object 2102:00h should be used for configuring it. 

![image](https://github.com/ezWheelSAS/swd_ros_controllers/assets/102302284/db3ff588-fdfc-4463-b7d6-f6b02bd0f7b3)


You can use the python CANOpenDBusClient library to configure it On/Off, during commissioning for instance, using: 
Internal CAN resistor OFF:
`CANOpenDBusClient.setValueBool(0x2102_00_00, 0)`
Internal CAN resistor ON: 
`CANOpenDBusClient.setValueBool(0x2102_00_00, 1)`

**Comment by ez-Support** [comment]
Another method could be used in the commissioning.py

`def update_network_parameters(node_id: int):

    network = NetworkParameters()

    network.node_id = node_id
    network.bit_timing = BitTiming.BT_1000
    network.rt_activated = True

    error = communication_client.setNetworkParameters(network)
    check(f"setNetworkParameters(node_id={node_id})", error)
  `  

You can choose wether to set `network.rt_activated` value to _True_/_False_ !

**Comment by suguruhamada1003910** [comment]
@ez-Support 

Thank you for reply!! I will try it!!
